/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jberger.pergen.node;

import org.jberger.pergen.analysis.Analysis;

@SuppressWarnings("nls")
public final class AMayBeZero extends PMayBeZero
{
    private TZero _zero_;
    private TTo _to_;

    public AMayBeZero()
    {
        // Constructor
    }

    public AMayBeZero(
        @SuppressWarnings("hiding") TZero _zero_,
        @SuppressWarnings("hiding") TTo _to_)
    {
        // Constructor
        setZero(_zero_);

        setTo(_to_);

    }

    @Override
    public Object clone()
    {
        return new AMayBeZero(
            cloneNode(this._zero_),
            cloneNode(this._to_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMayBeZero(this);
    }

    public TZero getZero()
    {
        return this._zero_;
    }

    public void setZero(TZero node)
    {
        if(this._zero_ != null)
        {
            this._zero_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._zero_ = node;
    }

    public TTo getTo()
    {
        return this._to_;
    }

    public void setTo(TTo node)
    {
        if(this._to_ != null)
        {
            this._to_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._to_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._zero_)
            + toString(this._to_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._zero_ == child)
        {
            this._zero_ = null;
            return;
        }

        if(this._to_ == child)
        {
            this._to_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._zero_ == oldChild)
        {
            setZero((TZero) newChild);
            return;
        }

        if(this._to_ == oldChild)
        {
            setTo((TTo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
