/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jberger.pergen.node;

import org.jberger.pergen.analysis.Analysis;

@SuppressWarnings("nls")
public final class TMany extends Token
{
    public TMany(String text)
    {
        setText(text);
    }

    public TMany(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMany(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMany(this);
    }
}
