CREATE TABLE AUTHOR (
   AUTHOR_ID INTEGER NOT NULL,
   firstname VARCHAR(50),
   lastname VARCHAR(50),
   birthdate DATE,
   death DATE,
   CONSTRAINT PK_AUTHOR PRIMARY KEY (AUTHOR_ID) 
   );
   
CREATE TABLE BOOK (
   BOOK_ID INTEGER NOT NULL,
   title VARCHAR(150),
   price DOUBLE,
   year INTEGER,
   SECTION_ID INTEGER NOT NULL,
   CONSTRAINT PK_BOOK PRIMARY KEY (BOOK_ID)
   );
   
CREATE TABLE SECTION (
   SECTION_ID INTEGER NOT NULL,
   name VARCHAR(255),
   CONSTRAINT PK_SECTION PRIMARY KEY (SECTION_ID)
   );
   
CREATE TABLE AUTHOR_BOOK (
   AUTHOR_BOOK_ID INTEGER NOT NULL auto_increment,
   AUTHOR_ID INTEGER NOT NULL,
   BOOK_ID INTEGER NOT NULL,
   CONSTRAINT PK_AUTHOR_BOOK PRIMARY KEY (AUTHOR_BOOK_ID)
   );
   
ALTER TABLE BOOK ADD( CONSTRAINT FK_BOOK_SECTION FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID));

ALTER TABLE AUTHOR_BOOK ADD( CONSTRAINT FK_AUTHOR_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID));

ALTER TABLE AUTHOR_BOOK ADD ( CONSTRAINT FK_AUTHOR_BOOK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID));

CREATE UNIQUE INDEX INDEX_AUTHOR1 ON AUTHOR(firstname, lastname, birthdate);

CREATE UNIQUE INDEX INDEX_BOOK1 ON BOOK(title, year);

CREATE UNIQUE INDEX INDEX_SECTION1 ON SECTION(name);
