/************************************************
 * This file was generated by ....
 ************************************************/

package org.jberger.pergen.prototype;

import java.util.ArrayList;
import java.util.Date;

/**
 * The Author object.
 */
public class Author {

    /**
     * The Id of the object.
     */
    private Integer id = null;

    /**
     * The firstname field.
     */
    private String firstname = null;

    /**
     * The lastname field.
     */
    private String lastname = null;

    /**
     * The birthdate field.
     */
    private Date birthdate = null;

    /**
     * The death field.
     */
    private Date death = null;

    /**
     * A list of Ids on Book objects.
     */
    private ArrayList<Integer> bookList = null;

    /**
     * Create a new Author.
     */
    public Author() {
        bookList = new ArrayList<Integer>();
    }

    /**
     * The birthdate field getter.
     * @return The birthdate field value.
     */
    public final Date getBirthdate() {
        return birthdate;
    }

    /**
     * The birthdate field setter.
     * @param newBirthdate The new birthdate value.
     */
    public final void setBirthdate(final Date newBirthdate) {
        birthdate = newBirthdate;
    }

    /**
     * The death field getter.
     * @return The death field value.
     */
    public final Date getDeath() {
        return death;
    }

    /**
     * The death field setter.
     * @param newDeath The new death value.
     */
    public final void setDeath(final Date newDeath) {
        death = newDeath;
    }

    /**
     * The firstname field getter.
     * @return The firstname field value.
     */
    public final String getFirstname() {
        return firstname;
    }

    /**
     * The firstname field setter.
     * @param newFirstname The new firstname value.
     */
    public final void setFirstname(final String newFirstname) {
        firstname = newFirstname;
    }

    /**
     * Id getter.
     * @return The Id of the object.
     */
    public final Integer getId() {
        return id;
    }

    /**
     * Id setter.
     * @param authorId The new Id value.
     */
    public final void setId(final Integer authorId) {
        id = authorId;
    }

    /**
     * The lastname field getter.
     * @return The lastname field value.
     */

    public final String getLastname() {
        return lastname;
    }

    /**
     * The lastname field setter.
     * @param newLastname The new lastname value.
     */
    public final void setLastname(final String newLastname) {
        lastname = newLastname;
    }

    /**
     * Add a Book Id.
     * @param bookId The Id of the Book to add.
     */
    public final void addBook(final Integer bookId) {
        bookList.add(bookId);
    }

    /**
     * Remove a Book Id.
     * @param bookId The Id of the book to remove.
     */
    public final void removeBook(final Integer bookId) {
        bookList.remove(bookId);
    }

    /**
     * Get a list of Book Ids.
     * @return A list of Book Ids.
     */
    public final ArrayList<Integer> getBookList() {
        return bookList;
    }
}
