/************************************************
 * This file was generated by ....
 ************************************************/

package org.jberger.pergen.prototype;

/**
 * Exception raised by DAOs if an error is detected while communicating
 * with the database.
 */
public class DAOException extends Exception {

    /**
     * Required for serialization.
     */
    static final long serialVersionUID = 200710190246666L;


    /**
     * Create a new DAOException.
     * @param message The message to display.
     * @param e The Exception raised by JDBC.
     */
    public DAOException(final String message, final Exception e) {
        super(message, e);
    }
}
