/************************************************
 * This file was generated by ....
 ************************************************/

package org.jberger.pergen.prototype;


/**
 * The Section object.
 */
public class Section {

    /**
     * The Id of the object.
     */
    private Integer id = null;

    /**
     * The name field.
     */
    private String name = null;

    /**
     * Create a new Section.
     */
    public Section() {
    }

    /**
     * Id getter.
     * @return The Id of the object.
     */
    public final Integer getId() {
        return id;
    }

    /**
     * Id setter.
     * @param sectionID The new Id value.
     */
    public final void setId(final Integer sectionID) {
        id = sectionID;
    }

    /**
     * The name field getter.
     * @return The name field value.
     */
    public final String getName() {
        return name;
    }

    /**
     * The name field setter.
     * @param newName The new name value.
     */
    public final void setName(final String newName) {
        name = newName;
    }
}
