/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAScript(AScript node);
    void caseAEntityDefinition(AEntityDefinition node);
    void caseAFieldInnerDefinition(AFieldInnerDefinition node);
    void caseARelationInnerDefinition(ARelationInnerDefinition node);
    void caseAUnicityInnerDefinition(AUnicityInnerDefinition node);
    void caseAMoreInnerDefinition(AMoreInnerDefinition node);
    void caseAFieldDefinition(AFieldDefinition node);
    void caseAOneRelationDefinition(AOneRelationDefinition node);
    void caseAManyRelationDefinition(AManyRelationDefinition node);
    void caseAUnicityDefinition(AUnicityDefinition node);
    void caseADateDataType(ADateDataType node);
    void caseAIntegerDataType(AIntegerDataType node);
    void caseARealDataType(ARealDataType node);
    void caseAStringDataType(AStringDataType node);
    void caseAStringLength(AStringLength node);
    void caseAMayBeZero(AMayBeZero node);
    void caseAMoreIdentifier(AMoreIdentifier node);

    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTComma(TComma node);
    void caseTSemicolon(TSemicolon node);
    void caseTEntity(TEntity node);
    void caseTHas(THas node);
    void caseTMany(TMany node);
    void caseTOne(TOne node);
    void caseTRequired(TRequired node);
    void caseTTo(TTo node);
    void caseTUnique(TUnique node);
    void caseTZero(TZero node);
    void caseTDate(TDate node);
    void caseTInteger(TInteger node);
    void caseTReal(TReal node);
    void caseTString(TString node);
    void caseTNumber(TNumber node);
    void caseTIdentifier(TIdentifier node);
    void caseTBlank(TBlank node);
    void caseTComment(TComment node);
    void caseEOF(EOF node);
}
